paginate:            5

markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

title:		           "Echo Chamber"
description:	       "A quiet corner of the internet where existential dread, weary cynicism, and tired introspection echo back on themselves."
author:              "A Disillusioned Witness"
