disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'G-9TGF3W0FGB'

menu:
- {name: 'About', url: 'about'}

pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
